# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: TestSolutions
    container: mcr.microsoft.com/dotnet/core/sdk:3.1

    steps:
      - script: >-
          docker build --build-arg PROJECT_NAME=Michal.Romanowski.Service1
          --target test-env . -t servicestest
      - script:
          id=$(docker create servicetest) 
          docker cp $id:/webapp/out-test/TestResults/testresults.trx ./results1.trx
          docker rm $id
      - task: PublishTestResults@2
        inputs:
          testRunner: VSTest
          testResultsFiles: '**/*.trx'
          failTaskOnFailedTests: true 
