parameters:
  - name: services
    type: object
    default: {}
  - name: buildConfiguration
    type: string
    default: "Release"
  - name: dotnetVersion
    type: string
    default: "3.1.403"
  - name: cakeVersion
    type: string
    default: "0.38.5"

jobs:
  - ${{ each service in parameters.services}}:
      - job: ${{ service.jobName }}
        displayName: "Build  ${{ service.projectName }}"
        variables:
          IMAGE_NAME: ${{ lower(service.projectName) }}
        steps:
          - task: UseDotNet@2
            displayName: "Use .NET Core sdk"
            inputs:
              packageType: sdk
              version: ${{ parameters.dotnetVersion }}
              installationPath: $(Agent.ToolsDirectory)/dotnet
          - script: dotnet tool install
              --global Cake.Tool
              --version ${{ parameters.cakeVersion }}
            displayName: "Install cake"
          - script: dotnet cake build.cake
              --projectName=${{ service.projectName}}
              --target=BuildAndTest
              --testOutputPath=$(Build.ArtifactStagingDirectory)/test-results
            displayName: "Build  ${{ service.projectName }} and ${{ service.projectName }}.Tests"
          - publish: $(Build.ArtifactStagingDirectory)
            artifact: ${{ service.artifactName }}
